name: Spark Driver - CentOS7
description: |
 Â Spark Driver
version: v2.1.0-rancher1
category: Frontend
maintainer: Mitsutoshi Kiuchi <m-kiuchi@creationline.com>
license: Apache2
projectURL: https://github.com/m-kiuchi/rancher-mkcatalog
minimum_rancher_version: v1.0.0
