name: WebGLEarth Demo
description: |
 Â WebGL Demo app running on Rancher and Mesos-Marathon
version: v0.0.1-rancher1
category: Toy Apps
maintainer: Mitsutoshi Kiuchi <m-kiuchi@creationline.com>
license: Apache2
projectURL: https://github.com/m-kiuchi/rancher-cattle-demo
minimum_rancher_version: v1.0.0
