kafka:
  privileged: true
  image: mkiuchicl/kafka
  environment:
    ZK_SERVICE: mesos/zookeeper
    MESOS_SERVICE: mesos/mesos-master
    SSHUSER: ${SSHUSER}
  ports:
  - 9092
  - 9093
  - 9094
  - 9095
  - 9096
  - 9097
  - 9098
  - 9099
  - 9100
  - 9101
  - 22
