name: CentOS7 for interactive frontend
description: |
 Â CentOS7 for interactive frontend
version: v7.3.1-rancher1
category: Frontend
maintainer: Mitsutoshi Kiuchi <m-kiuchi@creationline.com>
license: Apache2
projectURL: https://github.com/m-kiuchi/rancher-mkcatalog
minimum_rancher_version: v1.0.0
